version: "3.8"
services:
  frontend:
    container_name: react_app
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
  backend:
    container_name: node_backend
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8080:8080"
  # cache:
  #   container_name: postgres_cache
  #   build:
networks:
  internal:
