version: "3.8"
services:
  web:
    container_name: react_app
    build: .
    command: bash -c "npm install --quiet && npm run dev"
    working_dir: /usr/app
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - main
networks:
  main:
