version: "3.8"
services:
  web:
    container_name: react_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  benis:
    container_name: go_server
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
    ports:
      - "8080:8080"
networks:
  internal:
